rm -f adafruit-tinyusb-cdc.a
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/class/cdc/cdc_device.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/class/vendor/vendor_device.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/device/usbd_control.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/device/usbd.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/common/tusb_fifo.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/portable/microchip/samd/dcd_samd.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/tusb.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/Adafruit_USBD_Device.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/Adafruit_USBD_CDC.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/ports/samd/Adafruit_TinyUSB_samd.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/Adafruit_TinyUSB_API.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/core/USB/SAMD21_USBDevice.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/core/USB/USBCore.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/core/USB/CDC.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/class/hid/hid_device.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/class/msc/msc_device.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/class/midi/midi_device.c.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/hid/Adafruit_USBD_HID.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/msc/Adafruit_USBD_MSC.cpp.o
arm-none-eabi-ar rcs adafruit-tinyusb-cdc.a ./tmp-arduino_build/libraries/Adafruit_TinyUSB_Arduino/arduino/midi/Adafruit_USBD_MIDI.cpp.o
